obviously benign improvements from SDC

diff --git a/lib/svc/method/fs-joyent b/lib/svc/method/fs-joyent
--- a/lib/svc/method/fs-joyent
+++ b/lib/svc/method/fs-joyent
@@ -23,6 +23,12 @@
 
 set -o xtrace
 
+fatal()
+{
+    echo "Error: $1"
+    exit $SMF_EXIT_ERR_FATAL
+}
+
 . /lib/svc/share/smf_include.sh
 . /lib/svc/share/fs_include.sh
 
@@ -39,6 +45,35 @@ function destroy_zpools
     for pool in $(zpool list -p -o name | grep -v NAME) ; do
         zpool destroy -f ${pool}
     done
+}
+
+function mount_zfs
+{
+    local dataset=$1
+    local mountpoint=$2
+    local output=
+
+    #
+    # Try to mount the ZFS dataset.  If the mountpoint is busy, wait five
+    # seconds and try again.  Fail if the mount attempt returns EBUSY three
+    # consecutive times.
+    #
+    for i in {1..3}; do
+        output=$(mount -F zfs ${dataset} ${mountpoint} 2>&1)
+        if [[ $? -eq 0 ]]; then
+            break
+        fi
+
+        if [ "${output}" == "mount failed: Device busy" ]; then
+            sleep 5
+        else
+            echo ${output} 1>&2
+            return
+        fi
+    done
+
+    # The mount attempt must have failed
+    echo ${output} 1>&2
 }
 
 /bin/bootparams | grep "^noimport=true" >/dev/null
@@ -86,9 +121,9 @@ if [ $? -ne 0 ]; then
     # For the system zpool, mount and configure all system datasets
     zpool status -v ${SYS_ZPOOL}
     if [ $? -eq 0 ]; then
-        mount -F zfs ${SYS_ZPOOL}/var /var
-        mount -F zfs ${SYS_ZPOOL}/config /etc/zones
-        mount -F zfs ${SYS_ZPOOL}/opt /opt
+        mount_zfs ${SYS_ZPOOL}/var /var
+        mount_zfs ${SYS_ZPOOL}/config /etc/zones
+        mount_zfs ${SYS_ZPOOL}/opt /opt
         if [[ -n $(/bin/bootparams | grep '^headnode=true') ]]; then
           mkdir -p /opt/smartdc/agents/smf
           mount -O -F lofs /var/svc/manifest/site /opt/smartdc/agents/smf
@@ -97,7 +132,7 @@ if [ $? -ne 0 ]; then
   if [[ -n $(/bin/bootparams | grep '^headnode=true') || \
         -n $(/bin/bootparams | grep '^smartos=true') ]]; then
         mkdir /usbkey
-    mount -F zfs ${SYS_ZPOOL}/usbkey /usbkey
+    mount_zfs ${SYS_ZPOOL}/usbkey /usbkey
   fi
   if [[ -n $(/bin/bootparams | grep '^smartos=true') ]]; then
     mount -F lofs /usbkey/shadow /etc/shadow
@@ -120,7 +155,18 @@ if [ $? -ne 0 ]; then
             fatal "failed to set checksum=noparity on dump zvol"
         zpool set feature@multi_vdev_crash_dump=enabled ${SYS_ZPOOL} || \
             fatal "failed to enable multi_vdev_crash_dump ZFS feature"
-	dumpadm -y -d /dev/zvol/dsk/${SYS_ZPOOL}/dump
+	dumpadm -y -d /dev/zvol/dsk/${SYS_ZPOOL}/dump || \
+            fatal "failed to configure dump device"
+
+	zfs list -H -o name ${SYS_ZPOOL}/cores/global >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+	    # Booting for the first time on a CN whose cores dataset is setup
+	    # in the 6.x style.  Convert to the new style.
+	    zfs destroy -r ${SYS_ZPOOL}/cores
+	    zfs create -o compression=gzip -o mountpoint=none ${SYS_ZPOOL}/cores
+	    zfs create -o quota=10g -o mountpoint=/${SYS_ZPOOL}/global/cores \
+	        ${SYS_ZPOOL}/cores/global
+	fi
 
 	ln -s /${SYS_ZPOOL}/global/cores /cores
 
@@ -132,6 +178,15 @@ fi
 
 # The rest only applies to the headnode
 /bin/bootparams | grep "^headnode=true" >/dev/null || exit $SMF_EXIT_OK
+
+# If we rebooted during an upgrade, we're in deep trouble.
+if [ -d /var/upgrade_in_progress ]; then
+    echo "ERROR: An upgrade was in progress when the system rebooted." \
+        >/dev/console
+    echo "       The system is in an indeterminate state, unable to continue." \
+        >/dev/console
+    exit $SMF_EXIT_ERR_FATAL
+fi
 
 USBMOUNTPOINT=/mnt/`svcprop -p "joyentfs/usb_mountpoint" ${SMF_FMRI}`
 COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
@@ -148,7 +203,13 @@ fi
 
 function make_usb_copy
 {
-    $(cd ${USBMOUNTPOINT}; rsync -a --exclude private --exclude os * ${COPYINPOINT})
+    echo "" > /dev/console
+    echo "Moving files from USB boot device onto disk storage." > /dev/console
+    echo "This may take several minutes. Please note the time..." > /dev/console
+    echo "" > /dev/console
+    echo "" > /dev/console
+
+    $(cd ${USBMOUNTPOINT}; rsync -av --log-file=/dev/console --exclude private --exclude os * ${COPYINPOINT})
     if [[ -d ${USBMOUNTPOINT}/os ]]; then
         (cd ${USBMOUNTPOINT}/os ; \
             for dir in $(ls -d *); do
@@ -158,10 +219,14 @@ function make_usb_copy
                 source_dir=${dir}
                 target_dir=$(echo ${dir} | tr "[:lower:]" "[:upper:]")
                 mkdir -p ${COPYINPOINT}/os
+                echo "Copying: ${source_dir}/ ${COPYINPOINT}/os/${target_dir}" > /dev/console
                 rsync -a ${source_dir}/ ${COPYINPOINT}/os/${target_dir}
             done
         )
     fi
+
+    echo "" > /dev/console
+    echo "Done copying files from USB device" > /dev/console
 }
 
 mkdir -p ${USBMOUNTPOINT}
